<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0 ./static/models/scene.gltf --transform
Author: moyicat (https://sketchfab.com/moyicat)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chess-scene-pieces-blender-218776bed6144332ab41417badd5df6b
Title: Chess Scene Pieces / Blender
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { interactivity } from '@threlte/extras';
	export const ref = new Group();
	export const pieceName = '';

	interactivity();
	const gltf = useGltf('/src/lib/components/piece/scene-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();
</script>

<!-- svelte-ignore a11y-no-static-element-interactions -->
<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group position={[-0.75, 0, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
			<T.Group position={[0, 0, 2]}>
				<T.Mesh
					on:pointerover={() => console.log('Mouse pointer entered the object')}
					geometry={gltf.nodes.WhiteQueen_0.geometry}
					material={gltf.materials.Root}
					position={[0, 0, 0]}
					scale={0.1}
				/>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
