<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0 ./static/models/scene.gltf --transform
Author: moyicat (https://sketchfab.com/moyicat)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chess-scene-pieces-blender-218776bed6144332ab41417badd5df6b
Title: Chess Scene Pieces / Blender
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	export const ref = new Group();

	const gltf = useGltf('/src/lib/components/piece/scene-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group position={[-0.75, 0, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
			<T.Group position={[0, 0, 2]}>
				<T.Mesh
					geometry={gltf.nodes.WhiteKnight001_0.geometry}
					material={gltf.materials.Root}
					position={[3, 0, 0]}
					scale={1.33}
				/>
				<T.Mesh
					geometry={gltf.nodes.Rook001_0.geometry}
					material={gltf.materials.Root}
					position={[9, 0, 0]}
					scale={1.33}
				/>
				<T.Mesh
					geometry={gltf.nodes.PrimaryWhitePawn007_0.geometry}
					material={gltf.materials.White_Piece}
					position={[15, 0, 0]}
					scale={0.72}
				/>
				<T.Mesh
					geometry={gltf.nodes.PrimaryWhiteBishop001_0.geometry}
					material={gltf.materials.Root}
					position={[-3, 0, 0]}
					scale={0.24}
				/>
				<T.Mesh
					geometry={gltf.nodes.WhiteQueen_0.geometry}
					material={gltf.materials.Root}
					position={[-9, 0, 0]}
					scale={0.24}
				/>
				<T.Mesh
					geometry={gltf.nodes.WhiteKing_0.geometry}
					material={gltf.materials.Root}
					position={[-15, 0, 0]}
				/>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
