<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0 ./static/models/common-chess-pieces/scene.gltf --transform --types
Author: IreneMobilou (https://sketchfab.com/IreneMobilou)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chess-pieces-836e6b89b534450b8e0d577e4a476106
Title: Chess Pieces
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	type $$Props = Props<THREE.Group>;
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();

	type GLTFResult = {
		nodes: {
			Object_4: THREE.Mesh;
			Object_6: THREE.Mesh;
			Object_8: THREE.Mesh;
			Object_10: THREE.Mesh;
			Object_12: THREE.Mesh;
			Object_13: THREE.Mesh;
			Object_15: THREE.Mesh;
			Object_16: THREE.Mesh;
			Object_18: THREE.Mesh;
			Object_20: THREE.Mesh;
			Object_22: THREE.Mesh;
			Object_24: THREE.Mesh;
			Object_25: THREE.Mesh;
			Object_27: THREE.Mesh;
			Object_29: THREE.Mesh;
			Object_30: THREE.Mesh;
		};
		materials: {
			['Material.003']: THREE.MeshStandardMaterial;
			material_0: THREE.MeshStandardMaterial;
			['Material.002']: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/scene-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group position={[-17.89, 2.23, 2.06]} scale={[1.13, 1.2, 1.13]}>
			<T.Mesh geometry={gltf.nodes.Object_12.geometry} material={gltf.materials['Material.003']} />
			<T.Mesh geometry={gltf.nodes.Object_13.geometry} material={gltf.materials.material_0} />
		</T.Group>
		<T.Group
			position={[-28.25, 2.23, 2.11]}
			rotation={[-Math.PI, 0, -Math.PI]}
			scale={[1.16, 1.12, 1.16]}
		>
			<T.Mesh geometry={gltf.nodes.Object_15.geometry} material={gltf.materials['Material.003']} />
			<T.Mesh geometry={gltf.nodes.Object_16.geometry} material={gltf.materials['Material.003']} />
		</T.Group>
		<T.Group position={[2.55, 2.23, 2.1]} scale={[1.16, 1.12, 1.16]}>
			<T.Mesh geometry={gltf.nodes.Object_24.geometry} material={gltf.materials['Material.002']} />
			<T.Mesh geometry={gltf.nodes.Object_25.geometry} material={gltf.materials['Material.002']} />
		</T.Group>
		<T.Group
			position={[12.81, 2.23, 2.1]}
			rotation={[-Math.PI, 0, -Math.PI]}
			scale={[1.13, 1.2, 1.13]}
		>
			<T.Mesh geometry={gltf.nodes.Object_29.geometry} material={gltf.materials['Material.002']} />
			<T.Mesh geometry={gltf.nodes.Object_30.geometry} material={gltf.materials.material_0} />
		</T.Group>
		<T.Mesh
			geometry={gltf.nodes.Object_4.geometry}
			material={gltf.materials['Material.003']}
			position={[-23.02, 2.23, 2.08]}
			rotation={[-Math.PI, 1.57, -Math.PI]}
			scale={1.7}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_6.geometry}
			material={gltf.materials['Material.003']}
			position={[-12.78, 2.23, 2.03]}
			rotation={[-Math.PI, 0, -Math.PI]}
			scale={1.1}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_8.geometry}
			material={gltf.materials['Material.003']}
			position={[-7.61, 2.23, 2.04]}
			rotation={[-Math.PI, 0, -Math.PI]}
			scale={[0.82, 1, 0.82]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_10.geometry}
			material={gltf.materials['Material.003']}
			position={[-2.4, 2.23, 1.98]}
			scale={[1, 1.1, 1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_18.geometry}
			material={gltf.materials['Material.002']}
			position={[7.68, 2.23, 2.1]}
			rotation={[0, Math.PI / 2, 0]}
			scale={1.7}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_20.geometry}
			material={gltf.materials['Material.002']}
			position={[17.94, 2.23, 2.1]}
			scale={1.1}
		/>
		<T.Mesh geometry={gltf.nodes.Object_22.geometry} material={gltf.materials['Material.002']} />
		<T.Mesh
			geometry={gltf.nodes.Object_27.geometry}
			material={gltf.materials['Material.002']}
			position={[23.07, 2.23, 2.1]}
			scale={[0.82, 1, 0.82]}
		/>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
